### PR TITLE
refactor: preact example remove unused import

### PR DESCRIPTION
**Pull request by necipallef**

### CODE REVIEW

**Comment by ilfa** [comment]
Oh, I missed that it is no longer necessary for the preact JSX files.
@necipallef Can you do the same for `app.tsx`?

**Comment by necipallef** [comment]
> Oh, I missed that it is no longer necessary for the preact JSX files. @necipallef Can you do the same for `app.tsx`?

Done

**Comment by ilfa** [comment]
Hmm, I made additional research and it is better to keep `h` for our configuration. Build comment fails.

```
$ preact build --no-sw
✖ ERROR ./src/index.tsx
ERROR in ./src/index.tsx(9,6):
TS2304: Cannot find name 'h'.
error Command failed with exit code 1.
```

**Comment by necipallef** [comment]
Yeah, I agree. My bad

**Pull request closed without merging**
